# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'new_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
current_directory = os.path.dirname(os.path.abspath(__file__)) + '\\'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 680)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border: none;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet("background-color: rgb(165, 165, 165);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(677, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_minus = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minus.sizePolicy().hasHeightForWidth())
        self.btn_minus.setSizePolicy(sizePolicy)
        self.btn_minus.setStyleSheet("#btn_minus:hover {\n"
"    background-color: rgb(209, 209, 209);\n"
"}\n"
"#btn_minus:pressed {\n"
"    background-color: rgb(185, 185, 185);\n"
"}")
        self.btn_minus.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minus.setIcon(icon)
        self.btn_minus.setIconSize(QtCore.QSize(35, 25))
        self.btn_minus.setObjectName("btn_minus")
        self.horizontalLayout.addWidget(self.btn_minus)
        self.btn_window_restore = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_window_restore.sizePolicy().hasHeightForWidth())
        self.btn_window_restore.setSizePolicy(sizePolicy)
        self.btn_window_restore.setStyleSheet("#btn_window_restore:hover {\n"
"    background-color: rgb(209, 209, 209);\n"
"}\n"
"#btn_window_restore:pressed {\n"
"    background-color: rgb(185, 185, 185);\n"
"}")
        self.btn_window_restore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_window_restore.setIcon(icon1)
        self.btn_window_restore.setIconSize(QtCore.QSize(35, 25))
        self.btn_window_restore.setObjectName("btn_window_restore")
        self.horizontalLayout.addWidget(self.btn_window_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setStyleSheet("#btn_close:hover {\n"
"background-color: rgb(221, 148, 148);\n"
"}\n"
"#btn_close:pressed {\n"
"    background-color: rgb(214, 120, 120);\n"
"}")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setIconSize(QtCore.QSize(35, 25))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_webcam = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_webcam.sizePolicy().hasHeightForWidth())
        self.label_webcam.setSizePolicy(sizePolicy)
        self.label_webcam.setMinimumSize(QtCore.QSize(800, 600))
        self.label_webcam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_webcam.setStyleSheet("#label_webcam {\n"
"    background-color: rgb(207, 207, 207);\n"
"    border-radius: 10px;\n"
"}")
        self.label_webcam.setTextFormat(QtCore.Qt.AutoText)
        self.label_webcam.setScaledContents(False)
        self.label_webcam.setAlignment(QtCore.Qt.AlignCenter)
        self.label_webcam.setObjectName("label_webcam")
        self.horizontalLayout_3.addWidget(self.label_webcam)
        self.frame_infor = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_infor.sizePolicy().hasHeightForWidth())
        self.frame_infor.setSizePolicy(sizePolicy)
        self.frame_infor.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_infor.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_infor.setStyleSheet("#frame_infor {\n"
"    background-color: rgb(207, 207, 207);\n"
"\n"
"    border-radius: 10px;\n"
"}")
        self.frame_infor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infor.setObjectName("frame_infor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_infor)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_infor)
        self.widget.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"border-radius: 10px;\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_avatar = QtWidgets.QLabel(self.widget)
        self.label_avatar.setMinimumSize(QtCore.QSize(150, 150))
        self.label_avatar.setMaximumSize(QtCore.QSize(150, 150))
        self.label_avatar.setStyleSheet("#label_avatar {\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 10px;\n"
"    background-color: rgb(85, 255, 255);\n"
"}")
        self.label_avatar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_avatar.setText("")
        self.label_avatar.setPixmap(QtGui.QPixmap(current_directory + "images/images/PyDracula.png"))
        self.label_avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avatar.setObjectName("label_avatar")
        self.horizontalLayout_4.addWidget(self.label_avatar)
        spacerItem2 = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.frame_infor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_2.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_name = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_5.addWidget(self.label_name)
        spacerItem4 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.frame_infor)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_3.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(59, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.label_session = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_session.setFont(font)
        self.label_session.setObjectName("label_session")
        self.horizontalLayout_6.addWidget(self.label_session)
        spacerItem6 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.frame_infor)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_4.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem7 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.input_cccd = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_cccd.setFont(font)
        self.input_cccd.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"")
        self.input_cccd.setMaxLength(20)
        self.input_cccd.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_cccd.setObjectName("input_cccd")
        self.horizontalLayout_7.addWidget(self.input_cccd)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.frame_infor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_5.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_confirm = QtWidgets.QPushButton(self.widget_5)
        self.btn_confirm.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_confirm.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"  background-color: rgb(85, 255, 127);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 5px;\n"
"}")
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_9.addWidget(self.btn_confirm)
        self.btn_cancel = QtWidgets.QPushButton(self.widget_5)
        self.btn_cancel.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 85, 0);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 5px;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_9.addWidget(self.btn_cancel)
        self.verticalLayout_2.addWidget(self.widget_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_3.addWidget(self.frame_infor)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_webcam.setText(_translate("MainWindow", "Webcam"))
        self.label_name.setText(_translate("MainWindow", "Họ và tên"))
        self.label_4.setText(_translate("MainWindow", "Ca Thi : "))
        self.label_session.setText(_translate("MainWindow", "12C"))
        self.label_6.setText(_translate("MainWindow", "CCCD: "))
        self.btn_confirm.setText(_translate("MainWindow", "Xac nhan"))
        self.btn_cancel.setText(_translate("MainWindow", "Huy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
