# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'WindowAddStudentToSession.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
current_directory = os.path.dirname(os.path.abspath(__file__)) + '\\'


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(548, 466)
        Dialog.setStyleSheet("border: none;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(0, 116, 124);\n"
"    border-radius:10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(431, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_minus = QtWidgets.QPushButton(self.frame_4)
        self.btn_minus.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_minus.setStyleSheet("QPushButton{\n"
"    background: rgb(0, 116, 124);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 187, 201);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 144, 154);\n"
"}")
        self.btn_minus.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minus.setIcon(icon)
        self.btn_minus.setIconSize(QtCore.QSize(25, 25))
        self.btn_minus.setObjectName("btn_minus")
        self.horizontalLayout_3.addWidget(self.btn_minus)
        self.btn_close = QtWidgets.QPushButton(self.frame_4)
        self.btn_close.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_close.setBaseSize(QtCore.QSize(0, 0))
        self.btn_close.setStyleSheet("#btn_close:hover {\n"
"background-color: rgb(255, 71, 71);\n"
"    border-top-right-radius: 10px;\n"
"\n"
"}\n"
"#btn_close:pressed {\n"
"    background-color:rgb(190, 32, 32);\n"
"    border-top-right-radius: 10px;\n"
"\n"
"}")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(25, 25))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_19 = QtWidgets.QWidget(self.frame_3)
        self.widget_19.setStyleSheet("QWidget{\n"
"background-color: rgb(202, 202, 202);\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"}\n"
"")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem1 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.ip_search_student = QtWidgets.QLineEdit(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_search_student.sizePolicy().hasHeightForWidth())
        self.ip_search_student.setSizePolicy(sizePolicy)
        self.ip_search_student.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_search_student.setFont(font)
        self.ip_search_student.setStyleSheet("QLineEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ip_search_student.setObjectName("ip_search_student")
        self.horizontalLayout_18.addWidget(self.ip_search_student)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.btn_search_session = QtWidgets.QPushButton(self.widget_19)
        self.btn_search_session.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_search_session.setFont(font)
        self.btn_search_session.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search_session.setStyleSheet("QPushButton{\n"
"  background-color: #878787;\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(current_directory + "images/icons/icons8-search-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search_session.setIcon(icon2)
        self.btn_search_session.setObjectName("btn_search_session")
        self.horizontalLayout_18.addWidget(self.btn_search_session)
        spacerItem3 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget_19)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("QWidget{\n"
"background-color: rgb(202, 202, 202);\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.frame_5)
        self.listWidget.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(175, 254, 255);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle::vertical{\n"
"    background-color: rgb(0, 187, 201);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::handle::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::up-arrow::vertical, QScrollBar::down-arrow::vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page::vertical, QScrollBar::sub-page::vertical{\n"
"    background: none;\n"
"}\n"
"QListView::item{\n"
"    margin-top: 5px;\n"
"    border-radius: 10px;\n"
"    border-style: none;\n"
"}\n"
" QListView::item:hover {\n"
"    background-color: rgb(130, 195, 195);\n"
"    border-radius: 10px;\n"
" }\n"
" QListView::item:selected {\n"
"    background-color: rgb(130, 195, 195);\n"
" }\n"
"QListWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"pandding:10px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_search_session.setText(_translate("Dialog", "Tìm"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
