# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'row_inListSession.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 62)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.room_number = QtWidgets.QLabel(self.frame)
        self.room_number.setAlignment(QtCore.Qt.AlignCenter)
        self.room_number.setObjectName("room_number")
        self.horizontalLayout.addWidget(self.room_number)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.day = QtWidgets.QLabel(self.frame)
        self.day.setAlignment(QtCore.Qt.AlignCenter)
        self.day.setObjectName("day")
        self.horizontalLayout.addWidget(self.day)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.start_time = QtWidgets.QLabel(self.frame)
        self.start_time.setAlignment(QtCore.Qt.AlignCenter)
        self.start_time.setObjectName("start_time")
        self.horizontalLayout.addWidget(self.start_time)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.end_time = QtWidgets.QLabel(self.frame)
        self.end_time.setAlignment(QtCore.Qt.AlignCenter)
        self.end_time.setObjectName("end_time")
        self.horizontalLayout.addWidget(self.end_time)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_delete_session = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_session.sizePolicy().hasHeightForWidth())
        self.btn_delete_session.setSizePolicy(sizePolicy)
        self.btn_delete_session.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete_session.setStyleSheet("QPushButton{\n"
"border: none;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 71, 71);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(190, 32, 32);\n"
"}")
        self.btn_delete_session.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-delete-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete_session.setIcon(icon)
        self.btn_delete_session.setIconSize(QtCore.QSize(16, 16))
        self.btn_delete_session.setObjectName("btn_delete_session")
        self.horizontalLayout_2.addWidget(self.btn_delete_session)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.room_number.setText(_translate("MainWindow", "E102"))
        self.day.setText(_translate("MainWindow", "20-10-2002"))
        self.start_time.setText(_translate("MainWindow", "10:30"))
        self.end_time.setText(_translate("MainWindow", "12:30"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
