# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'row_inPageAddStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 46)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QWidget:hover{\n"
"    background-color: rgb(130, 195, 195);\n"
"}\n"
"\n"
"QWidget{\n"
"    border: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.id = QtWidgets.QLabel(self.frame)
        self.id.setAlignment(QtCore.Qt.AlignCenter)
        self.id.setObjectName("id")
        self.horizontalLayout.addWidget(self.id)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.fullname = QtWidgets.QLabel(self.frame)
        self.fullname.setAlignment(QtCore.Qt.AlignCenter)
        self.fullname.setObjectName("fullname")
        self.horizontalLayout.addWidget(self.fullname)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.dataOfBirth = QtWidgets.QLabel(self.frame)
        self.dataOfBirth.setAlignment(QtCore.Qt.AlignCenter)
        self.dataOfBirth.setObjectName("dataOfBirth")
        self.horizontalLayout.addWidget(self.dataOfBirth)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.email = QtWidgets.QLabel(self.frame)
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setObjectName("email")
        self.horizontalLayout.addWidget(self.email)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.gender = QtWidgets.QLabel(self.frame)
        self.gender.setAlignment(QtCore.Qt.AlignCenter)
        self.gender.setObjectName("gender")
        self.horizontalLayout.addWidget(self.gender)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setStyleSheet("background-color: rgb(74, 114, 118);")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_remove_student = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remove_student.sizePolicy().hasHeightForWidth())
        self.btn_remove_student.setSizePolicy(sizePolicy)
        self.btn_remove_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_remove_student.setStyleSheet("QPushButton{\n"
"border: none;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 71, 71);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(190, 32, 32);\n"
"}")
        self.btn_remove_student.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-delete-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_remove_student.setIcon(icon)
        self.btn_remove_student.setObjectName("btn_remove_student")
        self.verticalLayout_2.addWidget(self.btn_remove_student, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.id.setText(_translate("MainWindow", "1"))
        self.fullname.setText(_translate("MainWindow", "Ho Duy Phuc"))
        self.dataOfBirth.setText(_translate("MainWindow", "2002-22-22"))
        self.email.setText(_translate("MainWindow", "phuc@gmail.com"))
        self.gender.setText(_translate("MainWindow", "Nam"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
