# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'server_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
current_directory = os.path.dirname(os.path.abspath(__file__)) + '\\'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border: none;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(0, 116, 124);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(677, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_minus = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minus.sizePolicy().hasHeightForWidth())
        self.btn_minus.setSizePolicy(sizePolicy)
        self.btn_minus.setStyleSheet("#btn_minus:hover {\n"
"    background-color: rgb(0, 187, 201);\n"
"}\n"
"#btn_minus:pressed {\n"
"    background-color: rgb(0, 144, 154);\n"
"}")
        self.btn_minus.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minus.setIcon(icon)
        self.btn_minus.setIconSize(QtCore.QSize(35, 25))
        self.btn_minus.setObjectName("btn_minus")
        self.horizontalLayout.addWidget(self.btn_minus)
        self.btn_window_restore = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_window_restore.sizePolicy().hasHeightForWidth())
        self.btn_window_restore.setSizePolicy(sizePolicy)
        self.btn_window_restore.setStyleSheet("#btn_window_restore:hover {\n"
"    background-color: rgb(0, 187, 201);\n"
"}\n"
"#btn_window_restore:pressed {\n"
"background-color: rgb(0, 144, 154);\n"
"}")
        self.btn_window_restore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_window_restore.setIcon(icon1)
        self.btn_window_restore.setIconSize(QtCore.QSize(35, 25))
        self.btn_window_restore.setObjectName("btn_window_restore")
        self.horizontalLayout.addWidget(self.btn_window_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setStyleSheet("#btn_close:hover {\n"
"background-color: rgb(255, 71, 71);\n"
"    border-top-right-radius: 10px;\n"
"\n"
"}\n"
"#btn_close:pressed {\n"
"    background-color:rgb(190, 32, 32);\n"
"    border-top-right-radius: 10px;\n"
"\n"
"}")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setIconSize(QtCore.QSize(35, 25))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setMinimumSize(QtCore.QSize(250, 0))
        self.menu.setStyleSheet("#menu{\n"
"    background-color: rgb(135, 135, 135);\n"
"    border-bottom-left-radius: 10px;\n"
"\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.menu)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_camera = QtWidgets.QPushButton(self.frame_5)
        self.btn_camera.setEnabled(True)
        self.btn_camera.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_camera.setFont(font)
        self.btn_camera.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_camera.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_camera.setAutoFillBackground(False)
        self.btn_camera.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera.setIcon(icon3)
        self.btn_camera.setIconSize(QtCore.QSize(16, 16))
        self.btn_camera.setShortcut("")
        self.btn_camera.setCheckable(False)
        self.btn_camera.setAutoRepeat(False)
        self.btn_camera.setAutoExclusive(False)
        self.btn_camera.setAutoDefault(False)
        self.btn_camera.setDefault(True)
        self.btn_camera.setObjectName("btn_camera")
        self.verticalLayout_2.addWidget(self.btn_camera)
        self.btn_list_student = QtWidgets.QPushButton(self.frame_5)
        self.btn_list_student.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_list_student.setFont(font)
        self.btn_list_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_list_student.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-featured-playlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_list_student.setIcon(icon4)
        self.btn_list_student.setIconSize(QtCore.QSize(25, 25))
        self.btn_list_student.setObjectName("btn_list_student")
        self.verticalLayout_2.addWidget(self.btn_list_student)
        self.btn_list_session = QtWidgets.QPushButton(self.frame_5)
        self.btn_list_session.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_list_session.setFont(font)
        self.btn_list_session.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_list_session.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-briefcase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_list_session.setIcon(icon5)
        self.btn_list_session.setObjectName("btn_list_session")
        self.verticalLayout_2.addWidget(self.btn_list_session)
        self.verticalLayout_3.addWidget(self.frame_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 347, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_6 = QtWidgets.QFrame(self.menu)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border-bottom-left-radius: 10px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 163, 163);\n"
"    border-bottom-left-radius: 10px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(current_directory + "images/icons/cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout_3.addWidget(self.menu)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-bottom-right-radius: 10px;\n"
"    background-color: rgb(202, 202, 202);\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_25.setContentsMargins(-1, -1, 11, 11)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("#page{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.page.setObjectName("page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setStyleSheet("QFrame{\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.frame_7)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setStyleSheet("QLabel{\n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"  background-color: rgb(0, 187, 201);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"  background-color: rgb(0, 187, 201);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"  background-color: rgb(0, 187, 201);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_8.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.frame_7)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"  background-color: rgb(0, 187, 201);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_9.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"  background-color: rgb(0, 187, 201);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_10.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.widget_8)
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"  background-color: rgb(0, 187, 201);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_11.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addWidget(self.widget_8)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("#page_2{\n"
"background-color: rgb(202, 202, 202);\n"
"}\n"
"")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_12.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_9 = QtWidgets.QWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(687, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.temperature = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temperature.setFont(font)
        self.temperature.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(129, 165, 125);\n"
"}")
        self.temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature.setObjectName("temperature")
        self.horizontalLayout_7.addWidget(self.temperature)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.humidity = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity.setFont(font)
        self.humidity.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(115, 120, 212);\n"
"}")
        self.humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity.setObjectName("humidity")
        self.horizontalLayout_7.addWidget(self.humidity)
        self.verticalLayout_12.addWidget(self.widget_9)
        self.main_camera = QtWidgets.QLabel(self.page_2)
        self.main_camera.setStyleSheet("QLabel{\n"
"    background-color: rgb(227, 227, 227);\n"
"    border-radius: 5px;\n"
"}")
        self.main_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.main_camera.setObjectName("main_camera")
        self.verticalLayout_12.addWidget(self.main_camera)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("#page_3{\n"
"background-color: rgb(202, 202, 202);\n"
"}\n"
"")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_13.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_10 = QtWidgets.QWidget(self.frame_8)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.ip_search_student = QtWidgets.QLineEdit(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_search_student.sizePolicy().hasHeightForWidth())
        self.ip_search_student.setSizePolicy(sizePolicy)
        self.ip_search_student.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_search_student.setFont(font)
        self.ip_search_student.setStyleSheet("QLineEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ip_search_student.setObjectName("ip_search_student")
        self.horizontalLayout_8.addWidget(self.ip_search_student)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.btn_search_student = QtWidgets.QPushButton(self.widget_10)
        self.btn_search_student.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_search_student.setFont(font)
        self.btn_search_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search_student.setStyleSheet("QPushButton{\n"
"  background-color: #878787;\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(current_directory + "images/icons/icons8-search-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search_student.setIcon(icon7)
        self.btn_search_student.setObjectName("btn_search_student")
        self.horizontalLayout_8.addWidget(self.btn_search_student)
        spacerItem6 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.btn_add_student = QtWidgets.QPushButton(self.widget_10)
        self.btn_add_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add_student.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(current_directory + "images/icons/icons8-plus-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_student.setIcon(icon8)
        self.btn_add_student.setIconSize(QtCore.QSize(25, 25))
        self.btn_add_student.setObjectName("btn_add_student")
        self.horizontalLayout_8.addWidget(self.btn_add_student)
        self.verticalLayout_14.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.frame_8)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.verticalLayout_14.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.frame_8)
        self.widget_12.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.student_list = QtWidgets.QListWidget(self.widget_12)
        self.student_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.student_list.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(175, 254, 255);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle::vertical{\n"
"    background-color: rgb(0, 187, 201);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::handle::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::up-arrow::vertical, QScrollBar::down-arrow::vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page::vertical, QScrollBar::sub-page::vertical{\n"
"    background: none;\n"
"}\n"
"\n"
" QListView::item {\n"
"\n"
" }")
        self.student_list.setObjectName("student_list")
        self.horizontalLayout_10.addWidget(self.student_list)
        self.verticalLayout_14.addWidget(self.widget_12)
        self.verticalLayout_13.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("#page_4{\n"
"background-color: rgb(202, 202, 202);\n"
"}\n"
"")
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_11.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_9 = QtWidgets.QFrame(self.page_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_13 = QtWidgets.QWidget(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.btn_back_to_page_list_student = QtWidgets.QPushButton(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_to_page_list_student.sizePolicy().hasHeightForWidth())
        self.btn_back_to_page_list_student.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_back_to_page_list_student.setFont(font)
        self.btn_back_to_page_list_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(current_directory + "images/icons/icons8-back-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back_to_page_list_student.setIcon(icon9)
        self.btn_back_to_page_list_student.setObjectName("btn_back_to_page_list_student")
        self.verticalLayout_15.addWidget(self.btn_back_to_page_list_student)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem7)
        self.avatar = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatar.sizePolicy().hasHeightForWidth())
        self.avatar.setSizePolicy(sizePolicy)
        self.avatar.setMinimumSize(QtCore.QSize(150, 150))
        self.avatar.setStyleSheet("QLabel {\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar.setObjectName("avatar")
        self.verticalLayout_15.addWidget(self.avatar, 0, QtCore.Qt.AlignHCenter)
        self.btn_get_path_avatar = QtWidgets.QPushButton(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_get_path_avatar.sizePolicy().hasHeightForWidth())
        self.btn_get_path_avatar.setSizePolicy(sizePolicy)
        self.btn_get_path_avatar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_get_path_avatar.setFont(font)
        self.btn_get_path_avatar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_get_path_avatar.setStyleSheet("QPushButton{\n"
"  background-color: #878787;\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.btn_get_path_avatar.setObjectName("btn_get_path_avatar")
        self.verticalLayout_15.addWidget(self.btn_get_path_avatar, 0, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(20, 329, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem8)
        self.horizontalLayout_12.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.frame_9)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_16.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem9 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_16.addItem(spacerItem9)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_13.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.ip_fullname = QtWidgets.QLineEdit(self.widget_15)
        self.ip_fullname.setStyleSheet("QLineEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ip_fullname.setObjectName("ip_fullname")
        self.horizontalLayout_13.addWidget(self.ip_fullname)
        spacerItem10 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.verticalLayout_16.addWidget(self.widget_15)
        self.widget_26 = QtWidgets.QWidget(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(10)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_7 = QtWidgets.QLabel(self.widget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_26.addWidget(self.label_7)
        self.label_error_fullname = QtWidgets.QLabel(self.widget_26)
        self.label_error_fullname.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_error_fullname.setObjectName("label_error_fullname")
        self.horizontalLayout_26.addWidget(self.label_error_fullname)
        self.verticalLayout_16.addWidget(self.widget_26)
        self.widget_16 = QtWidgets.QWidget(self.widget_14)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.widget_16)
        self.label_16.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.ip_date_of_birth = QtWidgets.QDateEdit(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_date_of_birth.sizePolicy().hasHeightForWidth())
        self.ip_date_of_birth.setSizePolicy(sizePolicy)
        self.ip_date_of_birth.setStyleSheet("QDateEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}\n"
"\n"
"QDateEdit::up-arrow::vertical, QDateEdit::down-arrow::vertical{\n"
"}\n"
"\n"
"")
        self.ip_date_of_birth.setObjectName("ip_date_of_birth")
        self.horizontalLayout_14.addWidget(self.ip_date_of_birth)
        spacerItem11 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.verticalLayout_16.addWidget(self.widget_16)
        self.widget_27 = QtWidgets.QWidget(self.widget_14)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(10)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_8 = QtWidgets.QLabel(self.widget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_27.addWidget(self.label_8)
        self.label_error_dateOfBirth = QtWidgets.QLabel(self.widget_27)
        self.label_error_dateOfBirth.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_error_dateOfBirth.setObjectName("label_error_dateOfBirth")
        self.horizontalLayout_27.addWidget(self.label_error_dateOfBirth)
        self.verticalLayout_16.addWidget(self.widget_27)
        self.widget_20 = QtWidgets.QWidget(self.widget_14)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_15.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(80, 0))
        self.label_17.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.ip_email = QtWidgets.QLineEdit(self.widget_20)
        self.ip_email.setStyleSheet("QLineEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ip_email.setObjectName("ip_email")
        self.horizontalLayout_15.addWidget(self.ip_email)
        spacerItem12 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.verticalLayout_16.addWidget(self.widget_20)
        self.widget_28 = QtWidgets.QWidget(self.widget_14)
        self.widget_28.setObjectName("widget_28")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.widget_28)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(10)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_31 = QtWidgets.QLabel(self.widget_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(80, 0))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_28.addWidget(self.label_31)
        self.label_error_email = QtWidgets.QLabel(self.widget_28)
        self.label_error_email.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_error_email.setObjectName("label_error_email")
        self.horizontalLayout_28.addWidget(self.label_error_email)
        self.verticalLayout_16.addWidget(self.widget_28)
        self.widget_17 = QtWidgets.QWidget(self.widget_14)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_16.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtWidgets.QLabel(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.ip_gender = QtWidgets.QLineEdit(self.widget_17)
        self.ip_gender.setStyleSheet("QLineEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ip_gender.setObjectName("ip_gender")
        self.horizontalLayout_16.addWidget(self.ip_gender)
        self.label_19 = QtWidgets.QLabel(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.verticalLayout_16.addWidget(self.widget_17)
        self.widget_29 = QtWidgets.QWidget(self.widget_14)
        self.widget_29.setObjectName("widget_29")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_29)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(10)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_33 = QtWidgets.QLabel(self.widget_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(80, 0))
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_29.addWidget(self.label_33)
        self.label_error_gender = QtWidgets.QLabel(self.widget_29)
        self.label_error_gender.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_error_gender.setObjectName("label_error_gender")
        self.horizontalLayout_29.addWidget(self.label_error_gender)
        self.verticalLayout_16.addWidget(self.widget_29)
        self.widget_18 = QtWidgets.QWidget(self.widget_14)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btn_config_edit_student = QtWidgets.QPushButton(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_config_edit_student.sizePolicy().hasHeightForWidth())
        self.btn_config_edit_student.setSizePolicy(sizePolicy)
        self.btn_config_edit_student.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_config_edit_student.setFont(font)
        self.btn_config_edit_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_config_edit_student.setStyleSheet("QPushButton{\n"
"  background-color: #878787;\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"}")
        self.btn_config_edit_student.setObjectName("btn_config_edit_student")
        self.horizontalLayout_17.addWidget(self.btn_config_edit_student)
        self.verticalLayout_16.addWidget(self.widget_18)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem13)
        self.horizontalLayout_12.addWidget(self.widget_14)
        self.horizontalLayout_11.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("#page_5{\n"
"background-color: rgb(202, 202, 202);\n"
"}\n"
"")
        self.page_5.setObjectName("page_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_18.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_10 = QtWidgets.QFrame(self.page_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_19 = QtWidgets.QWidget(self.frame_10)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem14 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem14)
        self.ip_search_session = QtWidgets.QLineEdit(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_search_session.sizePolicy().hasHeightForWidth())
        self.ip_search_session.setSizePolicy(sizePolicy)
        self.ip_search_session.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_search_session.setFont(font)
        self.ip_search_session.setStyleSheet("QLineEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ip_search_session.setObjectName("ip_search_session")
        self.horizontalLayout_18.addWidget(self.ip_search_session)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem15)
        self.btn_search_session = QtWidgets.QPushButton(self.widget_19)
        self.btn_search_session.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_search_session.setFont(font)
        self.btn_search_session.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search_session.setStyleSheet("QPushButton{\n"
"  background-color: #878787;\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.btn_search_session.setIcon(icon7)
        self.btn_search_session.setObjectName("btn_search_session")
        self.horizontalLayout_18.addWidget(self.btn_search_session)
        spacerItem16 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem16)
        self.btd_add_session = QtWidgets.QPushButton(self.widget_19)
        self.btd_add_session.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btd_add_session.setText("")
        self.btd_add_session.setIcon(icon8)
        self.btd_add_session.setIconSize(QtCore.QSize(25, 25))
        self.btd_add_session.setObjectName("btd_add_session")
        self.horizontalLayout_18.addWidget(self.btd_add_session)
        self.verticalLayout_17.addWidget(self.widget_19)
        self.widget_21 = QtWidgets.QWidget(self.frame_10)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.verticalLayout_17.addWidget(self.widget_21)
        self.widget_22 = QtWidgets.QWidget(self.frame_10)
        self.widget_22.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.session_list = QtWidgets.QListWidget(self.widget_22)
        self.session_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.session_list.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(175, 254, 255);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle::vertical{\n"
"    background-color: rgb(0, 187, 201);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::handle::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::up-arrow::vertical, QScrollBar::down-arrow::vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page::vertical, QScrollBar::sub-page::vertical{\n"
"    background: none;\n"
"}\n"
"\n"
" QListView::item {\n"
"\n"
" }")
        self.session_list.setObjectName("session_list")
        self.horizontalLayout_20.addWidget(self.session_list)
        self.verticalLayout_17.addWidget(self.widget_22)
        self.verticalLayout_18.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setStyleSheet("#page_6{\n"
"background-color: rgb(202, 202, 202);\n"
"}\n"
"")
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_21.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_11 = QtWidgets.QFrame(self.page_6)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_25 = QtWidgets.QWidget(self.frame_11)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btn_back_to_page_list_session = QtWidgets.QPushButton(self.widget_25)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_back_to_page_list_session.setFont(font)
        self.btn_back_to_page_list_session.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back_to_page_list_session.setIcon(icon9)
        self.btn_back_to_page_list_session.setObjectName("btn_back_to_page_list_session")
        self.horizontalLayout_24.addWidget(self.btn_back_to_page_list_session)
        spacerItem17 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem17)
        self.ip_search_student_to_add = QtWidgets.QLineEdit(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_search_student_to_add.sizePolicy().hasHeightForWidth())
        self.ip_search_student_to_add.setSizePolicy(sizePolicy)
        self.ip_search_student_to_add.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_search_student_to_add.setFont(font)
        self.ip_search_student_to_add.setStyleSheet("QLineEdit{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ip_search_student_to_add.setObjectName("ip_search_student_to_add")
        self.horizontalLayout_24.addWidget(self.ip_search_student_to_add)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem18)
        self.btn_search_student_to_add = QtWidgets.QPushButton(self.widget_25)
        self.btn_search_student_to_add.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btn_search_student_to_add.setFont(font)
        self.btn_search_student_to_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search_student_to_add.setStyleSheet("QPushButton{\n"
"  background-color: #878787;\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"border-radius: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.btn_search_student_to_add.setIcon(icon7)
        self.btn_search_student_to_add.setObjectName("btn_search_student_to_add")
        self.horizontalLayout_24.addWidget(self.btn_search_student_to_add)
        spacerItem19 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.verticalLayout_19.addWidget(self.widget_25)
        self.widget_24 = QtWidgets.QWidget(self.frame_11)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_25 = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_23.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_23.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_23.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_23.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.widget_24)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_23.addWidget(self.label_30)
        self.verticalLayout_19.addWidget(self.widget_24)
        self.widget_23 = QtWidgets.QWidget(self.frame_11)
        self.widget_23.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.student_list_to_add = QtWidgets.QListWidget(self.widget_23)
        self.student_list_to_add.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.student_list_to_add.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(175, 254, 255);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle::vertical{\n"
"    background-color: rgb(0, 187, 201);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::handle::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::sub-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical{\n"
"    border: none;\n"
"    height: 15px;\n"
"    background-color: rgb(0, 187, 201);\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:hover{\n"
"    background-color: rgb(0, 208, 223);\n"
"}\n"
"\n"
"QScrollBar::add-line::vertical:pressed{\n"
"    background-color: rgb(0, 151, 162);\n"
"}\n"
"\n"
"QScrollBar::up-arrow::vertical, QScrollBar::down-arrow::vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page::vertical, QScrollBar::sub-page::vertical{\n"
"    background: none;\n"
"}\n"
"\n"
" QListView::item {\n"
"\n"
" }")
        self.student_list_to_add.setObjectName("student_list_to_add")
        self.horizontalLayout_22.addWidget(self.student_list_to_add)
        self.verticalLayout_19.addWidget(self.widget_23)
        self.horizontalLayout_21.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.page_6)
        self.horizontalLayout_25.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_camera.setText(_translate("MainWindow", "          Cameras"))
        self.btn_list_student.setText(_translate("MainWindow", "   Danh sách sinh viên"))
        self.btn_list_session.setText(_translate("MainWindow", "         Phiên học"))
        self.pushButton_6.setText(_translate("MainWindow", "            Cài đặt"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Xem chi tiết"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("MainWindow", "Xem chi tiết"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "Xem chi tiết"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "Xem chi tiết"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_5.setText(_translate("MainWindow", "Xem chi tiết"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_7.setText(_translate("MainWindow", "Xem chi tiết"))
        self.temperature.setText(_translate("MainWindow", "20*C"))
        self.humidity.setText(_translate("MainWindow", "50%"))
        self.main_camera.setText(_translate("MainWindow", "TextLabel"))
        self.btn_search_student.setText(_translate("MainWindow", " Tìm"))
        self.label_10.setText(_translate("MainWindow", "ID"))
        self.label_11.setText(_translate("MainWindow", "Họ và tên"))
        self.label_12.setText(_translate("MainWindow", "Ngày sinh"))
        self.label_13.setText(_translate("MainWindow", "Email"))
        self.label_14.setText(_translate("MainWindow", "Giới tính"))
        self.btn_back_to_page_list_student.setText(_translate("MainWindow", "Back"))
        self.avatar.setText(_translate("MainWindow", "avatar"))
        self.btn_get_path_avatar.setText(_translate("MainWindow", "Chọn từ file"))
        self.label_15.setText(_translate("MainWindow", "Họ và tên:"))
        self.label_error_fullname.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "Ngày sinh:"))
        self.label_error_dateOfBirth.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "Email:"))
        self.label_error_email.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "Giới tính:"))
        self.label_19.setText(_translate("MainWindow", "Vd: Nam/Nữ"))
        self.label_error_gender.setText(_translate("MainWindow", "TextLabel"))
        self.btn_config_edit_student.setText(_translate("MainWindow", "Xác Nhận"))
        self.btn_search_session.setText(_translate("MainWindow", "Tìm"))
        self.label_20.setText(_translate("MainWindow", "Số phòng"))
        self.label_21.setText(_translate("MainWindow", "Ngày diễn ra"))
        self.label_22.setText(_translate("MainWindow", "Thời gian bắt đầu"))
        self.label_23.setText(_translate("MainWindow", "Thời gian kết thúc"))
        self.label_24.setText(_translate("MainWindow", "Tình trạng"))
        self.btn_back_to_page_list_session.setText(_translate("MainWindow", "Back"))
        self.btn_search_student_to_add.setText(_translate("MainWindow", "Tìm"))
        self.label_25.setText(_translate("MainWindow", "ID"))
        self.label_26.setText(_translate("MainWindow", "Họ và tên"))
        self.label_27.setText(_translate("MainWindow", "Ngày sinh"))
        self.label_28.setText(_translate("MainWindow", "Email"))
        self.label_29.setText(_translate("MainWindow", "Giới tính"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
